// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQSrdfSxKkoVacb4JVyo14OgvgjRNlzCg',
    appId: '1:149822291351:web:cefd6d36201394e166d8d2',
    messagingSenderId: '149822291351',
    projectId: 'projekt-labor-zolkooo',
    authDomain: 'projekt-labor-zolkooo.firebaseapp.com',
    storageBucket: 'projekt-labor-zolkooo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRj0ivbbPVtUULFICT1VLnj0lvBfVRwgE',
    appId: '1:149822291351:android:b03c07aa690a5aed66d8d2',
    messagingSenderId: '149822291351',
    projectId: 'projekt-labor-zolkooo',
    storageBucket: 'projekt-labor-zolkooo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsPMBOgM_FHS6U99e7QbjSABQ_02eqxM',
    appId: '1:149822291351:ios:73b20bfefa5c6be966d8d2',
    messagingSenderId: '149822291351',
    projectId: 'projekt-labor-zolkooo',
    storageBucket: 'projekt-labor-zolkooo.firebasestorage.app',
    iosBundleId: 'com.example.projektLabor2',
  );
}
