// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsLcEZymxThZP7SxN2QGTqlfHik2Ma3g',
    appId: '1:1062295539229:web:5fa4b0696c8670797840f4',
    messagingSenderId: '1062295539229',
    projectId: 'projekt-labor-a4b1c',
    authDomain: 'projekt-labor-a4b1c.firebaseapp.com',
    storageBucket: 'projekt-labor-a4b1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGmJ76g7egdut1BQ6B5vhJC_IPIvGSh0',
    appId: '1:1062295539229:android:a0d9133c55d5f9137840f4',
    messagingSenderId: '1062295539229',
    projectId: 'projekt-labor-a4b1c',
    storageBucket: 'projekt-labor-a4b1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0k3X1RRDh5zO1R3b3vJrX_GSS9NsUrzo',
    appId: '1:1062295539229:ios:b36a2295381724c47840f4',
    messagingSenderId: '1062295539229',
    projectId: 'projekt-labor-a4b1c',
    storageBucket: 'projekt-labor-a4b1c.firebasestorage.app',
    iosBundleId: 'com.nagyvazsony.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxsLcEZymxThZP7SxN2QGTqlfHik2Ma3g',
    appId: '1:1062295539229:web:7c868c529376d5cf7840f4',
    messagingSenderId: '1062295539229',
    projectId: 'projekt-labor-a4b1c',
    authDomain: 'projekt-labor-a4b1c.firebaseapp.com',
    storageBucket: 'projekt-labor-a4b1c.firebasestorage.app',
  );
}