name: mobile_app
description: Nagyvazsony turist app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  mobile_scanner: ^7.1.4
  url_launcher: ^6.3.1
  latlong2: ^0.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0
  google_maps_flutter: ^2.13.1
  path_provider: ^2.1.5
  firebase_crashlytics: ^5.1.0
  firebase_performance: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/var.jpg
    - assets/loading_screen.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo_launcher.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo_launcher.png
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#F2EBDD"
  color_dark: "#F2EBDD"
  image: assets/logo.png
  image_dark: assets/logo.png
  android_12:
    color: "#F2EBDD"
    color_dark: "#F2EBDD"
    image: assets/logo.png
    image_dark: assets/logo.png
  android: true
  ios: true
  web: false




